trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'azure-container-app'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build the application'

- task: Docker@2
  inputs:
    containerRegistry: 'yourACRServiceConnection'  # Update with your ACR service connection name
    repository: 'youracrname.azurecr.io/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: 'Container'
